Fitting
PostonLab/IVIM_fit pull request #6
Opened 2024-07-01 22:05 UTC by DimuthuHemachandra

## Proposed changes

Describe the changes implemented in this pull request. If the changes fix a bug or resolves a feature request, be sure to link the issue. Please explain the issue and how the changes address the issue.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionalitiy)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] Code has been run through the `poe quality` task
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2024-07-01 22:08 UTC, DimuthuHemachandra commented
I have added two models to be used in IVIM fitting for testing. Names of the other models can be added as necessary. Each model will be fitted in available directions and this will run in parallel. Once the models are fitted in each direction, D, Dstar and F images will be concatenated to make a 4D image.

2024-07-14 20:50 UTC, etpeterson requested changes

2024-07-14 20:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    valid_id = S0 > (0.5 * np.median(S0[S0 > 0]))
Why is this fancy normalization necessary?

2024-07-14 20:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    # Calculate mean S0 signal, replace nan values with 0
This comment worries me. Why are there nan values?

2024-07-14 20:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    num_cores = 4  # Specify the number of cores you want to use
Make a variable?

2024-07-14 20:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    bval_count = len(np.unique(bval))
Why unique? There are probably going to be duplicate b=0 values. But then the `max_bval` isn't inside the unique above so that seems to create a mismatch.

2024-07-14 20:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +import matplotlib.pyplot as plt
Unused?

2024-07-14 20:50 UTC, etpeterson commented on pyproject.toml
> +joblib = "^1.4.2"
Unused?

2024-07-14 20:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    f_map = np.reshape(f_map, [sx, sy, sz])
Create it with the correct shape initially and reshape won't be necessary. Same below.

2024-07-15 01:14 UTC, DimuthuHemachandra commented on ivim_fit/workflow/rules/diffusion/fitting.smk
> +        mask=rules.synthstrip_b0_fix_header.output.mask,
Yes.

2024-07-15 01:14 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/concat_fitted.py
> +        print(algorithm)
That was just for testing. Will remove that.

2024-07-15 01:19 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/concat_fitted.py
> +df_concat.to_csv(snakemake.output.concatted, index=False)
I used it because Snakemake allows you to use it directly like this without creating additional variables. But can clean it up.

2024-07-15 01:24 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    # Insert S0 into the subset data
S0 is in the data, this is trying to filter volumes belongs to one direction. I used it in the same way as they have implemented in the juypyter notebook you sent to me.

2024-07-15 01:29 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    # Identify valid ids based on S0 signal (greater than half of its median value)
This is also something they have implemented in the Jupyter notebook you sent me. What they are trying to do is, to find a mean value to normalize the data, they have first selected voxels with higher intensity. Otherwise the image mean value will be very low.

2024-07-15 01:35 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
I agree. What we discussed was to use the docker container to do the fitting. I ran into memory issues and was difficult to parallelize. I will explain this at our next meeting.

2024-07-15 01:41 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +repo_url = "https://github.com/merelvdthiel/TF2.4_IVIM-MRI_CodeCollection.git"  # IVIM fit repo
Again, I used what that Jupyter notebook was using. It will clone only once, if the repo is there, it wont clone again. If this is not the correct version of the repo to use, I will change it.

2024-07-15 01:43 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    valid_id = S0 > (0.5 * np.median(S0[S0 > 0]))
I just followed what that Jupyter notebook was doing. Some sort of data normalization is good to use, I think. I am also not sure.

2024-07-15 01:45 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    # Calculate mean S0 signal, replace nan values with 0
Also take from that Jupyter NB. I think this step is taken to clean up data normalization. Incase there is a nan value, the normalization would be bad.

2024-07-15 01:46 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    num_cores = 4  # Specify the number of cores you want to use
Yes, will put this into the config file as a variable.

2024-07-15 01:52 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    bval_count = len(np.unique(bval))
This is working only with only style of bval files. (How we have in our dataset. Ex:if we have a bval file like  0, 0, 20, 50, 100, 0, 50, 20,100, 0, 20, 50, 100. I wanted a vector that contains 0,20 50, 100. Unique values forst give me those numbers). If the bval is formatted differently, we will have to use a different approach. This whole process is to slice us volumes with the same direction.

2024-07-15 01:54 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +import matplotlib.pyplot as plt
Yes. Will remove that.

2024-07-15 01:56 UTC, DimuthuHemachandra commented on pyproject.toml
> +joblib = "^1.4.2"
tqdm = "^4.66.4"
joblib = "^1.4.2" 
These two are used within the ivim repo. Can remove matplotlib = "^3.9.0"

2024-07-15 02:03 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    f_map = np.reshape(f_map, [sx, sy, sz])
I used it as how they have implemented in the Jupyter Notebook. I will see if that approach is possible.

2024-07-15 03:49 UTC, etpeterson requested changes

2024-07-15 03:49 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +repo_url = "https://github.com/merelvdthiel/TF2.4_IVIM-MRI_CodeCollection.git"  # IVIM fit repo
The main is here https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection

This still clones the whole repo as is. Each time this file is run it will at least try, so maybe each time the pipeline is run it gets cloned?

Also, there's no branch or commit selection here so we just get whatever is in main. That's something to be avoided. Definitely a docker image would be far more stable.

2024-07-15 03:49 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/concat_fitted.py
> +df_concat.to_csv(snakemake.output.concatted, index=False)
One downside is that if there is any testing of the repo it runs the global part, so this would always be run.

2024-07-15 03:49 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
Ok.

2024-07-15 03:49 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    # Insert S0 into the subset data
I would take the notebook as a guide but as far as I know it's relatively untested. Another guide is the other file I showed you: https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/blob/main/WrapImage/nifti_wrapper.py

I would definitely use both but with suspicion.

2024-07-15 03:49 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    bval_count = len(np.unique(bval))
Also troubling even is that it's assuming the acquisition order rather than getting it from the data. If we changed from direction in the outer loop to inner then it would silently break this.

It also seems to assume that there's a single ignored image at the beginning. That's true in this case, but again a risky assumption to make.

2024-07-15 22:12 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +    bval_count = len(np.unique(bval))
I will keep this as WOP for now. I will think of a better way to implement this in a way it would work for any bval file.

2024-07-15 22:19 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/concat_fitted.py
> +df_concat.to_csv(snakemake.output.concatted, index=False)
It will run only if the output files are missing. Already run steps will not rerun in snakemake.

2024-07-15 22:21 UTC, DimuthuHemachandra commented
Fitting method is implemented. Working only for one specific type of bval files. WOP to make it compatible for any bval.

2024-07-15 22:22 UTC, merged