Dwi to t1
PostonLab/IVIM_fit pull request #7
Opened 2024-07-15 22:26 UTC by DimuthuHemachandra

## Proposed changes

Describe the changes implemented in this pull request. If the changes fix a bug or resolves a feature request, be sure to link the issue. Please explain the issue and how the changes address the issue.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionalitiy)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [x] Code has been run through the `poe quality` task
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

2024-07-16 04:34 UTC, etpeterson requested changes

2024-07-16 04:34 UTC, etpeterson commented on ivim_fit/workflow/rules/diffusion/fitting.smk
> +        interpolation="Linear",
Probably should be something better than linear.

2024-07-16 04:34 UTC, etpeterson commented on ivim_fit/workflow/rules/diffusion/synthsr.smk
> +        restrict_deformation=get_restrict_deformation,
It looks like this is estimating EPI deformation. Isn't this already done by FSL?

2024-07-16 04:34 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +df = pd.read_csv(snakemake.input.resampled)
I'm not quite following this. What is it parallelizing? It looks like it's dominated by disk access so I don't think multi threading will help performance here.

Also, and I think I commented on this in the now closed PR, doesn't FSL have this operation in `fslmaths -Tmean`

2024-07-17 04:12 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +with Pool() as pool:
This is at least the 2nd time this pattern has shown up. If you want to keep parallelizing things in this way you probably should make a generic function or decorator for this to prevent duplication.

2024-08-26 23:25 UTC, DimuthuHemachandra commented on ivim_fit/workflow/rules/diffusion/fitting.smk
> +        interpolation="Linear",
I am using Greedy tool for registration. So normally Linear is sufficient for transformation with the xfm file coming from Greedy. We can use something like nearest neighbor if the linear is not doing a good job. What I can see from our output is that, Linear is good enough. But if you think   nearest neighbor or something non-linear is necessary, we can change that. Might take longer time as we have 4D volumes though.

2024-08-26 23:31 UTC, DimuthuHemachandra commented on ivim_fit/workflow/rules/diffusion/synthsr.smk
> +        restrict_deformation=get_restrict_deformation,
This rule is commented out. So not in use.

2024-08-26 23:54 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +df = pd.read_csv(snakemake.input.resampled)
What is being parallelized here is, now we have 4D images from D, D* and F coming from multiple algorithms. Each 4D image is averaged in parallel. I used a python script here because it is easy to deal with CSV files and file naming. `fslmaths -TmeanIf` would have worked. If am to use fsl, then I have to use a fsl container. Which is difficult within a python script (unless u use nipype). Time wise, both takes about the same time. So, I didn't see any advantage. Happy to go over this at our next meeting.

2024-08-27 00:03 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +with Pool() as pool:
Not sure what is being duplicated here. `pool.map()` is what I am using to run a defined method in parallel. Could you pleas explain for which part I can use a generic function? Or we can go over it at our next meeting.

2024-08-28 04:50 UTC, etpeterson requested changes

2024-08-28 04:50 UTC, etpeterson commented on ivim_fit/workflow/rules/diffusion/fitting.smk
> +        interpolation="Linear",
Isn't this ANTs? At least it's using the ANTs container. It also looks like Greedy isn't symmetric as long as we're OK with always operating in atlas space.

This is just applying the warping, right?

2024-08-28 04:50 UTC, etpeterson commented on ivim_fit/workflow/rules/diffusion/reg_dwi_to_t1.smk
> +rule qc_get_t1_edges:
I'm just noticing this qc stuff. What's that?

2024-08-28 04:50 UTC, etpeterson commented on ivim_fit/workflow/rules/diffusion/reg_dwi_to_t1.smk
> +"""
Maybe remove commented stuff? Also seems to be duplicated elsewhere.

2024-08-28 04:50 UTC, etpeterson commented on ivim_fit/workflow/rules/diffusion/synthsr.smk
> +        restrict_deformation=get_restrict_deformation,
Oh, so then remove?

2024-08-28 04:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +df = pd.read_csv(snakemake.input.resampled)
I guess I'd have to see the csv file but it seems odd to write a whole script to do something that fsl has a command for. As for csv parsing, doesn't snakemake support python, so couldn't you preprocess the inputs in snakemake and send them in in a nice way that would be easy for FSL?

2024-08-28 04:50 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +with Pool() as pool:
It's been a while since my comment but I think the idea was to write a wrapper around the multiprocessing stuff so as to avoid this structure each time.

But I also question the use of multiple processes in this case because it's dominated by disk access, so maybe that's another thing to discuss.

2024-10-28 22:46 UTC, DimuthuHemachandra commented on ivim_fit/workflow/rules/diffusion/fitting.smk
> +        interpolation="Linear",
Yes, this is just applying the warping, using the transformation from Greedy.

2024-10-28 22:46 UTC, DimuthuHemachandra commented on ivim_fit/workflow/rules/diffusion/reg_dwi_to_t1.smk
> +"""
I removed these comments.

2024-10-28 22:47 UTC, DimuthuHemachandra commented on ivim_fit/workflow/rules/diffusion/reg_dwi_to_t1.smk
> +rule qc_get_t1_edges:
This is something I am still working on.

2024-10-28 22:49 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +with Pool() as pool:
I removed the parallel process approach for calculating the mean. I couldn't fit that into the fitting process as you suggested due to a file naming issue. So I kept it separate as usual, but removed parallel process.

2024-10-29 04:32 UTC, etpeterson requested changes

2024-10-29 04:32 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/fit.py
> +subprocess.run(["git", "clone", repo_url])
Cloning is not the greatest, but is ok. However, cloning from someone's personal repository without a specific version is not reproducible and can only lead to frustration down the line.

2024-10-29 04:32 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
I think this can now be removed?

2024-10-29 04:34 UTC, etpeterson commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +with Pool() as pool:
What file naming issue? It's our pipeline so shouldn't we have control over the file names?

2024-12-20 22:15 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
> +with Pool() as pool:
I will explain this over our next meeting. Anyway the averaging takes less than 10 seconds for the whole subject with or without parallelizing. So technically it doesn't really matter which approach we use.

2024-12-20 22:16 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/fit.py
> +subprocess.run(["git", "clone", repo_url])
I will update this so that we can specify the version.

2024-12-20 22:16 UTC, DimuthuHemachandra commented on ivim_fit/workflow/scripts/fitting/mean_fitted.py
Yes.

2024-12-30 17:48 UTC, merged